### ISSUE TITLE
Redis proxy in non-cluster mode

### ISSUE THREAD

**Issue by zhmylove** [iph0/Redis-ClusterRider#5]
Running the code with non-clustered Redis leads to exception:
```
# perl -MRedis::ClusterRider -e 'Redis::ClusterRider->new(startup_nodes=>["127.0.0.1:6379"])'
[cluster_info] ERR This instance has cluster support disabled,  at /usr/local/share/perl/5.28.1/Redis.pm line 275.
```
From my perspective it would be great if Redis.pm was transparently used instead.

@iph0, I could implement such a feature in the future, if its OK from your side.

**Comment by iph0** [comment]
It will be great.
